CREATE DATABASE test2;
USE test2;

CREATE TABLE category(
id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(255) DEFAULT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE product(
id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(255)  DEFAULT NULL,
p_price FLOAT DEFAULT NULL,
c_id INT(11) DEFAULT NULL,
CONSTRAINT fk_product_category
FOREIGN KEY (c_id)
REFERENCES category(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
//  mybatis_generator  参考 https://blog.csdn.net/m0_37884977/article/details/79240950